version: '3.9'

services:
  apache:
    image: httpd
    ports:
      - 80:80
    restart: always
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./src:/var/www/html/
      - ./front/build:/var/www/html/statistics
    depends_on:
      - db
  php-fpm:
    build:
      context: .
      dockerfile: FPM_Dockerfile
    restart: always
    volumes:
      - ./src:/var/www/html/
      - ./custom.php.ini:/usr/local/etc/php/conf.d/custom.php.ini
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_LOGIN=${MYSQL_LOGIN}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_ADMIN=${BOT_ADMIN}
  db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - sqlData:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:8080
    environment:
      - PMA_ARBITRARY=1
      - APACHE_PORT=8080
volumes:
  sqlData:
